### ISSUE TITLE
duvida a por os valores de dicionario json

### ISSUE THREAD

**Issue by prolo09** [prolo09/Pari_trabalho2#2]
a ordem dos valores nao é a correta

**Comment by alexdannyvaladares** [comment]
de que valores ?

**Comment by prolo09** [comment]
e verdade vou modar o titulo

os valore do dicionario deveria estar por a ordem BGR e nao esta a dar 
e a sua ordem tambem deveria ser com forme o stor a pos

**Comment by PedroTavares1998** [comment]
Nao e importante porque o programa ar_paint vai buscar os valores pelo nome e nao pela ordem

**Comment by prolo09** [comment]
expimenti com neste codigo mas nao deu 

import json
>>> from collections import OrderedDict
>>> values = OrderedDict([('profile','testprofile'), 
                          ('format', 'RSA_RC4_Sealed'), 
                          ('enc_key', '...'), 
                          ('request', '...')])
>>> json.dumps(values, sort_keys=False)
'{"profile": "testprofile", "format": "RSA_RC4_Sealed", "enc_key": "...", "request": "..."}'

**Comment by prolo09** [comment]
os valores ja ficaram ajeitados estao uma formataçao bonita 
pode ficar assim
