### ISSUE TITLE
como mostrar so a maior aria

### ISSUE THREAD

**Issue by prolo09** [prolo09/Pari_trabalho2#4]
detetamos a maior aria mas nao conseguimos mostra-la ainda na tela

**Comment by alexdannyvaladares** [comment]
Podemos escolher uma area minima  baseada na  maior area ( do genero 85% )  e eleminaar tudo abaixo disso

**Comment by prolo09** [comment]
Sera que é preciso mostra essa tela o deixamos so mesmo  o codigo a correr por tras?

**Comment by alexdannyvaladares** [comment]
não sei, mas  mostrar não custa nada .... é preciso é limpa-las melhor depois

**Comment by prolo09** [comment]
ok mas nao pomos pois so vai pertovar o resto do programa so ccom mais uma janela e ja se nota que esta a funcionar aquilo de por a aproximar o objto
