### ISSUE TITLE
Melhorar a limpeza da imagem

### ISSUE THREAD

**Issue by alexdannyvaladares** [prolo09/Pari_trabalho2#6]
É necessario limpa melhor a imagem

**Comment by prolo09** [comment]
estamos a usar erode e depois limitar a arie pequenas 
ahas que deviamos por mais alguma morflogia ?

**Comment by alexdannyvaladares** [comment]
se calhar um `cv2.medianBlur`  ? que achas?

**Comment by prolo09** [comment]
ja esta tratado
